### ISSUE TITLE
How can i get difference from two JSON files?

### ISSUE THREAD

**Issue by AkshayBaldia** [alphahelix00/jsonequals#3]
I have two JSON files and trying to compare it with you given example **ComparisonTest.java** but I can see only build the successful message. I am new to Gradle project can you please help?

**Comment by kvnxiao** [comment]
Take a look at the `JsonCompareResult` that is returned when you do a comparison between two JSON roots.

**Comment by AkshayBaldia** [comment]
Can you explain it with an example because I don't know how to use it?

**Comment by kvnxiao** [comment]
The [Javadocs](http://kevinxiao.ca/jsonequals/) and [source code](https://github.com/kvnxiao/jsonequals/blob/master/src/main/java/com/github/kvnxiao/jsonequals/JsonCompareResult.java) are available at your disposal.

**Comment by kvnxiao** [comment]
You'll want to check the `successMessages` and `inequalityMessages` from the comparison result.

**Comment by AkshayBaldia** [comment]
Actually, I want the difference between two JSON

**Comment by kvnxiao** [comment]
The `inequality` messages will tell you only the field names that have different values.

**Comment by AkshayBaldia** [comment]
Okie thanks, but I don't know how to use it. Can you please share a sample code?

**Comment by AkshayBaldia** [comment]
Getting logger error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I have added the jar file but still getting the bug.

**Comment by kvnxiao** [comment]
You need a SLF4J implementation like `Logback`. Issues here on github is not for troubleshooting these unrelated problems. Take your time to learn the Java ecosystem and how to use build tools like Gradle/Maven, and take your time to use Google for problems entirely unrelated to this project.
