### ISSUE TITLE
Ignore Order

### ISSUE THREAD

**Issue by Ripul89** [alphahelix00/jsonequals#4]
Hi All,
I am new to this, i am using this to compare two json string. Inside json string it is having multiple array and the order is not fixed on the second json. Both value is coming form different source.
How can i compare the string and ignore the order same like JSONCompareMode.LENIENT.

Please suggest

**Comment by Ripul89** [comment]
@kvnxiao  Please do reply

**Comment by kvnxiao** [comment]
Hi @Ripul89 , unfortunately based on json specifications, the usage of arrays in json is meant to preserve order, so your use case itself seems "incorrect". My suggestion would be to fix your two sources to output the arrays in order, if possible.

This project serves its purpose as being a simple deep-equality checker, but I don't have the time to maintain and introduce new changes like this. You are welcome to open a PR that adds this functionality as you see fit.
